### ISSUE TITLE
sqlite运行报错

### ISSUE THREAD

**Issue by tianxia007** [xphsc/easyjdbc#2]
spring:
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /
      # 响应页面默认后缀
      suffix: .jsp
  #数据库配置
  datasource:
    #错位空格会导致数据库配置无效
    datasource-name: default
    driver-class-name: org.sqlite.JDBC
    username:
    password: 123456
    #url: jdbc:sqlite:classpath:db.db
    url: jdbc:sqlite:D:\1dev\git_workspace\filemanager\src\main\resources\db2.db

报错:

2018-09-12 22:22:31.588 DEBUG 12936 --- [-nio-90-exec-12] c.xphsc.easyjdbc.executor.FindExecutor   : ==> SQL:[ select * from user ]
2018-09-12 22:22:31.590  INFO 12936 --- [-nio-90-exec-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2018-09-12 22:22:32.662 ERROR 12936 --- [-nio-90-exec-12] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.sqlite.SQLiteException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database)
	at org.sqlite.core.DB.newSQLException(DB.java:909) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.core.DB.newSQLException(DB.java:921) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.core.DB.throwex(DB.java:886) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.core.DB.prepare(DB.java:227) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.SQLiteConfig.apply(SQLiteConfig.java:140) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:85) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[sqlite-jdbc-3.23.1.jar:na]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[sqlite-jdbc-3.23.1.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117) ~[HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365) ~[HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194) ~[HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460) [HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534) [HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) [HikariCP-2.7.9.jar:na]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) [HikariCP-2.7.9.jar:na]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151) [spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115) [spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78) [spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371) [spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:446) [spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:456) [spring-jdbc-5.0.8.RELEASE.jar:5.0.8.RELEASE]
怎么处理呢

**Comment by xphsc** [comment]
请检查数据库是否存在，路径是否准确
